version: "3"
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - postgres
    
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: "@!pass123"
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge